# Usando a versão mais recente do Node.js (Node.js 20)
FROM node:20

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos de definição do pacote (package.json e package-lock.json) para o contêiner
COPY package*.json ./

# Instalar as dependências do Node.js
RUN npm install

# Copiar todos os arquivos do seu projeto para o contêiner
COPY . .

# Compilar o TypeScript para JavaScript
RUN npm run build

# Expor a porta que o servidor backend vai rodar
EXPOSE 3000

# Comando para rodar o servidor, após compilar o código TypeScript
CMD ["node", "dist/index.js"]
