services:
  db:
    image: mysql
    container_name: mysql_container_maisprati_frontend_project
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_maisprati_frontend_project
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db

volumes:
  db_data:
